[package]
name = "onchange"
version = "0.1.1"
edition = "2021"
authors = ["Thomas Kapocsi"]
license = "MIT OR Apache-2.0"
description = "A simple cli to await file changes"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
